### ISSUE TITLE
[TN237] resend SMS bug

### ISSUE THREAD

**Issue by bastian-purrer** [human-internet/humanid-weblogin#30]

**Comment by ccrawford4** [comment]
Resolved - PR created

**Comment by ccrawford4** [comment]
Changes were made to prevent users from resending the code until AFTER 60 seconds has passed with a timer on the front-end. All changes were since made and moved into the develop branch. The changes to web-login need to be reflected on the amazon ec2 instance

**Comment by bastian-purrer** [comment]
@ccrawford4 review: just shows a white screen for me now on web
![image](https://github.com/human-internet/humanid-weblogin/assets/46710651/bc3b1cc0-b897-4c97-8a39-51db7423549b)

**Comment by bastian-purrer** [comment]
@ccrawford4 does this bug affect web and the SDKs, or only web? does it need testing across platforms? (particularly worried about the RN sdk).

**Comment by tech-lead-humanID** [comment]
@bastian-purrer for the first comment, append /demo to the end of the url. As for the count-down from my understanding this fix should only impact the SDK's that rely on the web-login. So any Native apps that are using the react-native SDK will not be impacted by these changes but I can confirm with Kofi to make sure

**Comment by bastian-purrer** [comment]
@ccrawford4 approved for production

**Comment by tech-lead-humanID** [comment]
@ccrawford4  has this been completed?

**Comment by bastian-purrer** [comment]
layout not consistent, just have a quick look at the layout why it's behaving like that @Lunasocute

**Comment by tech-lead-humanID** [comment]
> layout not consistent, just have a quick look at the layout why it's behaving like that [@Lunasocute](https://github.com/Lunasocute)

The layout is inconsistency in this way, the "resend code" option appeared during the 1 min countdown. 
The "resend code" should be up right at the same time of the 1min countdown end.

Screenshot:
![Image](https://github.com/user-attachments/assets/eb6507d3-e2d3-4f37-972c-6a12915e52d8)

**Comment by bastian-purrer** [comment]
@Lunasocute this one is also urgent, when can we release this? if stuck, please immediately get the indo team on this as well. thx!
