### ISSUE TITLE
TN-249 Add Privacy Policy & T&S link

### ISSUE THREAD

**Issue by bastian-purrer** [human-internet/humanid-weblogin#36]
* Use same font, fontsize & color as the 
"Learn more" text.
* Make sure it's well aligned so the left and right end 
of the text has equal distance from the edge of the screen. 
Ensure it works without linebreak on mobile as well. 
If not possible, add links below each other.
• Add sufficient distance from the "Send SMS" button

Links will be (bas will create when you folks are ready):
docs.human-id.org/privacy-policy
docs.human-id.org/sms-terms-and-conditions

![Image](https://github.com/human-internet/humanid-weblogin/assets/46710651/6cd2be9f-f6ae-4ff9-addc-5d0f4d23f592)

These links can show identical for all languages [fyi this page is available in 26+ languages] and does not need to be translated

**Comment by falhar** [comment]
@bastian-purrer @ccrawford4 I tried to open [https://docs.human-id.org/privacy-policy](https://docs.human-id.org/privacy-policy) and [https://docs.human-id.org/sms-terms-and-conditions](https://docs.human-id.org/sms-terms-and-conditions) but got page not found, are those links correct?

**Comment by bastian-purrer** [comment]
@falhar kita pakai gitbooks di docs.human-id.org, jadi aku bisa buat pages itu tanpa tech support //. i can create these pages without tech support

**Comment by ccrawford4** [comment]
Current Status: Need to move onto staging (already merged into main)

**Comment by bastian-purrer** [comment]
@ccrawford4 looks good, approved

**Comment by bastian-purrer** [comment]
@ccrawford4 please give me 24 to add the content for the links before promoting. thx

**Comment by bastian-purrer** [comment]
@Lunasocute @falhar please promote

**Comment by bastian-purrer** [comment]
please promote asap @Lunasocute
