### ISSUE TITLE
TN-279 Login redesign

### ISSUE THREAD

**Issue by aubreymechard** [human-internet/humanid-weblogin#42]
- [ ] Decrease line height(line spacing) on page 1 header (mobile) to 125%
- [ ] Center align all content on page 1 (mobile) - buttons are currently NOT yet
- [ ] Move —-or—-- line to be evenly spaced between the two buttons on page 1
- [ ] Change button border radius to 10px on all pages
- [ ] Change button width across all pages to be consistent with page 1 button
- [ ] Change button text to small caps on all pages. E.g.
                 Redirect Now instead of REDIRECT NOW
                 Send SMS with Verification Code instead of SEND SMS WITH VERIFICATION CODE

Link to supporting document: [https://docs.google.com/document/d/1FheAU_r9Q0H8rnBejALHsO6Ji7eMCgeia0EGQXgOgSI/edit](url)

**Comment by bastian-purrer** [comment]
@aubreymechard please provide link that works
